version: '2.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3307:3306

  api:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
    - 3001:3001
    - 8000:8000
   depends_on:
    - db
   volumes:
    - api-data:/home/app/code/node_modules
    - ./:/home/app/code

volumes:
  api-data:
  my-datavolume: